healthcare_data:

  target: dev
  outputs:
    dev:
      type: duckdb
      threads: 3
      temp_directory: '/.tmp'
      plugins:
        - module: excel
      extensions:
        - httpfs
        - parquet
        - aws
      use_credential_provider: aws